name: DUMMY

on:
  pull_request:
    branches: [ master ]

jobs:
  timeout_job:
    runs-on: enclave_host
    steps:
     - name: Timeout
       run: |
         timeout 1m ./mini_pipeline/dmesg.sh || code=$?; if [[ $code -ne 124 && $code -ne 0 ]]; then exit $code; fi
