name: Dummy

on:
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    runs-on: enclave_host
    defaults:
      run:
        shell: 'script --command "bash {0}"'
    steps:
      - name: Step1
        timeout-minutes: 2
        run: |
          sudo virsh console ubuntu18.04 || code=$?; if [[ $code -ne 124 && $code -ne 0 ]]; then exit $code; fi
        
  build2:
    runs-on: log_centos78
    steps:
      - name: Run a multi-line script
        run: |
          timeout 40m virsh console centos7.8 || code=$?; if [[ $code -ne 124 && $code -ne 0 ]]; then exit $code; fi
