name: Dummy

on:
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    runs-on: enclave_host
    steps:
      - name: Step1
        uses: docker://evaneos/ssh-action:0.1.0
        with:
          ssh_config: |
            ForcePTTYAllocation yes
          commands: |
            timeout 40m sudo virsh console centos7.8 || code=$?; if [[ $code -ne 124 && $code -ne 0 ]]; then exit $code; fi
          
  build2:
    runs-on: log_centos7.8
    steps:
      - name: Run a multi-line script
        run: |
          timeout 40m virsh console centos7.8 || code=$?; if [[ $code -ne 124 && $code -ne 0 ]]; then exit $code; fi
