name: Test Action

on:     
  pull_request:

jobs:
  main:
    runs-on: p_pipeline
    steps:

    - name: fetching pr details
      run: |
         echo "$GITHUB_REF"
         PR_NUMBER=$(echo $GITHUB_REF | awk 'BEGIN { FS = "/" } ; { print $3 }')
         echo "$PR_NUMBER"
         cd 
         rm -rf XRT
         echo "${{github.event.pull_request.number}}"
         
    - name: Test workflow
      run: |
         echo "Test is working"
         bash /home/sdausr/actions-runner/teset.sh
