name: Test Action

on:     
  pull_request:

jobs:
  main:
    runs-on: p_pipeline
    steps:

    - name: Test workflow
      run: |
         echo "Test is working"
         bash /home/sdausr/actions-runner/teset.sh
    - name: second run
      run: |
         bash /home/sdausr/draft_script1.sh
