name: Test Action

on:     
  pull_request:

jobs:
  main:
    runs-on: p_pipeline
    steps:

    - name: fetching pr details
      run: |
         echo "$GITHUB_REF"
         PR_NUMBER=$(echo $GITHUB_REF | awk 'BEGIN { FS = "/" } ; { print $3 }')
         echo "$PR_NUMBER"
         cd 
         rm -rf XRT
         git clone "https://github.com/eshwar-xilinx/XRT.git"
         gr pr checkout $PR_NUMBER
         
    - name: Test workflow
      run: |
         echo "Test is working"
         bash /home/sdausr/actions-runner/teset.sh
