name: Dummy

on:
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"        
  build2:
    runs-on: centos7.8
    steps:
      - name: Run a multi-line script
        run: |
          echo $PATH
          ls -al ~/
      - name : Check if working directory identified
        run: ls -al
        working-directory: ~/
