name: Dummy

on:
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    runs-on: enclave_host
    defaults:
      run:
        shell: 'script -q -c "timeout 30s bash {0}" exit 0' 
    steps:
      - name: Step1
        timeout-minutes: 2
        run: sudo virsh console ubuntu18.04
          
  build2:
    runs-on: log_centos78
    defaults:
      run:
        shell: 'script -q -c "timeout 30s bash {0}" exit 0' 
    steps:
      - name: Run a multi-line script
        timeout-minutes: 3
        run: sudo virsh console centos7.8
