name: Test Action

on:     
  pull_request:

jobs:
  binary_check:
    runs-on: p_pipeline
    steps:

    - name: Install Dependencies
      run: |
        sudo apt update
        sudo apt install jq curl
    - name: Binary Check
      run: |
         echo "Test is working"
