name: Test Action

on:     
  pull_request:

jobs:
  vm_revert:
    runs-on: p_pipeline
    steps:
    - name: refreshing vm
      run: |
          sudo ./launch_vm.sh

  main:
    needs: vm_revert
    runs-on: ${{matrix.os}}
    strategy:
      matrix:
        os: [ pr_pipeline, pr2_pipeline ]
    steps:
    - name: XRT
      run: |
          sudo ./build_xrt.sh --pr_id ${{github.event.pull_request.number}}
          sudo ./install_xrt.sh
          sudo ./test_xrt.sh
      working-directory: /home/eshwar/
     
  dettach:
    if: ${{ always() }}
    needs: main
    runs-on: p_pipeline
    steps:
    - name: dettach_card
      run: |
          sudo ./dettach_card.sh
