name: Test Action

on:     
  pull_request:

jobs:
  vm_creation:
    runs-on: p_pipeline
    steps:
    - name: refreshing vm
      run: |
          echo "${{github.event.pull_request.number}} is the PR number"
          echo "$(readlink -f .) is the current path"
          sudo virsh list
          sudo ./launch_vm.sh

#  main:
#    needs: vm_creation
#    runs-on: pr_pipeline
#    steps:
#    - uses: actions/checkout@v2
#    - name: XRT
#      run: |
#          echo "Building deb/rpm packages"
#          ./build_xrt.sh --pr_id ${{github.event.pull_request.number}}
#          ./install_xrt.sh
#          ./test_xrt.sh
