name: Mini Pipeline

on:     
  pull_request:

jobs:
  vm_creation:
    runs-on: enclave_host
    defaults:
      run:
        working-directory: /home/sdausr/mini_pipeline
    steps:
    - name: Creating a VM from snapshot on enclave host
      run: |
          sudo ./create_vm.sh
    - name: Attaching Cards to VM
      run: | 
          sudo ./attach_cards.sh

  verification:
    needs: vm_creation
    runs-on: ${{matrix.os}}
    defaults:
      run:
        working-directory: /home/eshwar
    timeout-minutes: 50
    strategy:
      matrix:
        os: [ u200_18.04, u50_7.8 ]
      fail-fast: false
    steps:
    - name: build XRT
      run: |
          sudo ./setup.sh
          sudo ./build_xrt.sh --pr_id ${{github.event.pull_request.number}}
    - name: install XRT
      run: |
          sudo ./install_xrt.sh
    - name: reset card
      timeout-minutes: 5
      run: |
          sudo ./reset_card.sh
    - name: examine card
      if: always()
      timeout-minutes: 5
      run: |
          sudo ./examine.sh
    - name: validate card
      if: always()
      timeout-minutes: 5
      run: |
          sudo ./validate.sh
    - name: drivers reloading
      if: always()
      timeout-minutes: 10
      run: |
          sudo ./stress_drivers.sh
    - name: Success
      if: always()
      run: |
          sudo ./ssignal.sh
