# This is a basic workflow to help you get started with Actions

name: XRT pipeline

# Controls when the workflow will run
on:

  pull_request:

jobs:
  main:
    runs-on: enclave_host
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      # Runs a set of commands using the runners shell
      - name: vm creation
        run: |
          .github/scripts/create_vm.sh
          .github/scripts/attach_cards.sh
          
      - name: Build XRT
        run: |
          .github/scripts/build_xrt.sh
          
      - name: Install XRT
        run: .github/scripts/install_xrt.sh
        
      - name: reset card
        timeout-minutes: 5
        run: |
          sudo .github/scripts/reset_card.sh
          
      - name: examine card
        if: always()
        timeout-minutes: 5
        run: |
          sudo ./github/scripts/examine.sh
          
      - name: validate card
        if: always()
        timeout-minutes: 5
        run: |
            sudo ./github/scripts/validate.sh
