
name: Pipeline

on:
  pull_request:

jobs:
 build:
   runs-on: enclave_host
   defaults:
      run:
        working-directory: /home/sdausr/mini_pipeline
   steps:
     - name: Initialisation
       run: |
         sudo ./create_vm.sh
     - name: Attaching Cards to VM
       run: | 
         sudo ./attach_cards.sh
         
############################ Steps for Ubuntu18.04 ####################################

     - name: build XRT Ubuntu18.04
       if: always()
       run: |
          ${{secret.SSH}} ${ubuntu18.04} ./build_xrt.sh "--pr_id" "${{github.event.pull_request.number}}"
     - name: install XRT Ubuntu18.04
       if: always()
       run: |
          ${{secret.SSH}} ${ubuntu18.04} ./install_xrt.sh
     - name: reset card Ubuntu18.04
       if: always()
       timeout-minutes: 5
       run: |
          ${{secret.SSH}} ${ubuntu18.04} ./reset_card.sh
     - name: examine card Ubuntu18.04
       if: always()
       timeout-minutes: 5
       run: |
          ${{secret.SSH}} ${ubuntu18.04} ./examine.sh
     - name: validate card Ubuntu18.04
       if: always()
       timeout-minutes: 5
       run: |
          ${{secret.SSH}} ${ubuntu18.04} ./validate.sh
          
#########################  Steps for CentOS7.8  #######################################

     - name: build XRT centos7.8
       if: always()
       run: |
          ${{ secrets.SSH }} ${centos7.8} ./build_xrt.sh "--pr_id" "${{github.event.pull_request.number}}"
     - name: install XRT centos7.8
       if: always()
       run: |
          ${{ secrets.SSH }} ${centos7.8} ./install_xrt.sh
     - name: reset card centos7.8
       if: always()
       timeout-minutes: 5
       run: |
          ${{ secrets.SSH }} ${centos7.8} ./reset_card.sh
     - name: examine card centos7.8
       if: always()
       timeout-minutes: 5
       run: |
          ${{ secrets.SSH }} ${centos7.8} ./examine.sh
     - name: validate card centos7.8
       if: always()
       timeout-minutes: 5
       run: |
          ${{ secrets.SSH }} ${centos7.8} ./validate.sh
          
#################################################################################################
#      Dettach the cards attached to the VM. If not removed, next PR is going to be affected.   #
#################################################################################################

     - name: dettach_card 
       if: always()
       run: |
          sudo ./dettach_card.sh
