name: Pipeline Test 2

on:     
  pull_request:

jobs:
  XRT:
    runs-on: u200_18.04
    defaults:
      run:
        shell: bash
    timeout-minutes: 40
    steps:
    - name: Setup
      run: sudo ./setup.sh
      working-directory: /home/eshwar
    - name: Checkout PR
      uses: actions/checkout@v2
    - name: Check Status
      run: |
        chmod +x .github/scripts/*.sh
        .github/scripts/build_xrt.sh
