name: Pipeline Test

on:     
  pull_request:

jobs:
  preparing_vm:
    runs-on: enclave_host
    defaults:
      run:
        working-directory: /home/sdausr/mini_pipeline
    steps:
    - name: Creating a VM from snapshot on enclave host
      run: |
          ./create_vm.sh
    - name: Attaching Cards to VM
      run: | 
          ./attach_cards.sh
          
  collecting_log:
    runs-on: enclave_host
    steps:
    - name: Dummy
      timeout-minutes: 5
      run: |
          ./dummy_test.sh
          
  verification:
    needs: preparing_vm
    runs-on: ${{matrix.os}}
    defaults:
      run:
        shell: bash
        working-directory: /home/eshwar
    timeout-minutes: 50
    strategy:
      matrix:
        os: [ u200_18.04, u50_7.8, u250_20.04 ]
      fail-fast: false
    steps:
   # - name: checkout repo
    #  uses: actions/checkout@v2
    - name: build XRT
      run: |
          sudo ./setup.sh
          ./build_xrt.sh --pr_id ${{github.event.pull_request.number}}
          
    - name: install XRT
      run: |
          ./install_xrt.sh
          
    - name: reset card
      timeout-minutes: 5
      run: |
          ./reset_card.sh
          
    - name: examine card
      if: always()
      timeout-minutes: 5
      run: |
          ./examine.sh
          
    - name: validate card
      if: always()
      timeout-minutes: 5
      run: |
          ./validate.sh
          
    - name: drivers reloading
      if: always()
      timeout-minutes: 10
      run: |
          ./stress_drivers.sh
          
    - name: Upload the build artifacts
      uses: actions/upload-artifact@v2
      with:
        name: XRT build
        path: /home/eshwar/XRT/build
        
    - name: Success
      if: always()
      run: |
          ./ssignal.sh
