name: WorkingTest

on:     
  pull_request:

jobs:
  vm_creation:
    runs-on: enclave_host
    defaults:
      run:
        shell: bash
    steps:
    - name: Creating a VM from snapshot on enclave host
      run: |
        sudo ./create_vm.sh
      working-directory: /home/sdausr/mini_pipeline/utils/kvm
    - name: Attaching Cards to VM
      run: | 
        sudo ./attach_cards.sh
      working-directory: /home/sdausr/mini_pipeline/utils/kvm

  XRT:
    needs: vm_creation
    runs-on: ${{matrix.os}}
    defaults:
      run:
        working-directory: /home/eshwar
        shell: bash
    timeout-minutes: 40
    strategy:
      matrix:
        os: [ u200_18.04, u50_7.8 ]
      fail-fast: false
    steps:
    - name: build XRT
      run: |
        sudo ./setup.sh
        ./tests/build_xrt/build_xrt.sh ${{github.event.pull_request.number}}
    - name: XRT build artifacts
      if: always()
      uses: actions/upload-artifact@v2
      with:
        name: Build Artifacts
        path: /home/eshwar/XRT/build/Release
    - name: install XRT
      run: |
        ./tests/install_xrt/install_xrt.sh
    - name: reset card
      timeout-minutes: 5
      run: |
        ./tests/reset/reset_card.sh
    - name: examine card
      timeout-minutes: 5
      run: |
        ./tests/examine/examine.sh
    - name: validate card
      timeout-minutes: 5
      run: |
        ./tests/validate/validate.sh
    - name: drivers reloading
      timeout-minutes: 10
      run: |
        ./tests/stress/stress_drivers.sh
          
  dmesg_centos78:
    runs-on: log_centos78
    needs: XRT
    defaults:
      run:
        shell: bash
    if: always()
    steps:
    - name: Console Output
      run: |
        sudo ./console.sh centos7.8
      working-directory: /home/sdausr/mini_pipeline/utils/console
    - name: Clean
      if: always()
      run: touch /mnt/nfs_share/unlock.txt
      
  dmesg_ubuntu18:
    runs-on: log_ubuntu18
    needs: XRT
    defaults:
      run:
        shell: bash
    if: always()
    steps:
    - name: Console Output
      run: |
        sudo ./console.sh ubuntu18.04
      working-directory: /home/sdausr/mini_pipeline/utils/console
    - name: Clean
      if: always()
      run: touch /mnt/nfs_share/unlock.txt
