# This is a basic workflow to help you get started with Actions

name: working through test

# Controls when the workflow will run
on:
  pull_request:

jobs:
  collect_log:
    runs-on: log_collector
    defaults:
      run:
        shell: bash
        working-directory: /home/eshwar
    if: always()
    steps:
    - name: Ubuntu18
      run: ./print.sh ubuntu18
    - name: Ubuntu20
      run: ./print.sh ubuntu20
