# This is a basic workflow to help you get started with Actions

name: working through test

# Controls when the workflow will run
on:
  pull_request:

jobs:

  lock:
    runs-on: ubuntu-latest
    steps:
      - name: check for the lock
        run: |
          .github/scripts/checkforlock.sh
  first:
    runs-on: enclave_host
    needs: lock
    steps:
      - name: first job
        run: |
          echo "LOCK_ENCLAVE=true" >> $GITHUB_ENV
          echo "This is first job"
          sleep 5m
  main:
    needs: first
    runs-on: ubuntu-latest
    steps:
      - name: dependent
        run: |
          echo "this is the dependent job"
          sleep 10m
  last:
    needs: main
    runs-on: enclave_host
    steps:
      - name: last job
        run: |
          echo "LOCK_ENCLAVE=false" >> $GITHUB_ENV
          echo "this is the last job"
          sleep 5m
