# This is a basic workflow to help you get started with Actions

name: working through test

# Controls when the workflow will run
on:
  pull_request:

jobs:

  preparing_vm:
    runs-on: enclave_host
    defaults:
      run:
        working-directory: /home/sdausr/mini_pipeline
    steps:
    - name: Creating a VM from snapshot on enclave host
      run: |
          ./create_vm.sh
    - name: Attaching Cards to VM
      run: | 
          ./attach_cards.sh
          
  collecting_log:
    needs: preparing_vm
    runs-on: log_collector
    defaults:
      run:
        working-directory: /home/eshwar
        shell: bash
    steps:
    - name: Initiate netconsole
      run: |
          nc -l -u 6666 > centos_dmesg.log &
          sleep 20m
          cat centos_dmesg.log
          
  verification:
    needs: preparing_vm
    runs-on: u50_7.8
    defaults:
      run:
        shell: bash
        working-directory: /home/eshwar
    timeout-minutes: 50
    steps:
   # - name: checkout repo
    #  uses: actions/checkout@v2
    - name: nothing 
      run: sudo modprobe options netconsole netconsole=6666@10.23.83.52/enp1s0,6666@10.23.83.236/52:54:00:63:62:49
      
    - name: build XRT
      run: |
          sudo ./setup.sh
          ./build_xrt.sh --pr_id ${{github.event.pull_request.number}}
          
    - name: install XRT
      run: |
          ./install_xrt.sh
          
    - name: reset card
      timeout-minutes: 5
      run: |
          ./reset_card.sh
          
    - name: examine card
      if: always()
      timeout-minutes: 5
      run: |
          ./examine.sh
    
    - name: validate card
      if: always()
      timeout-minutes: 5
      run: |
          ./validate.sh
